### ISSUE TITLE
Incompatible with 4.6 due to civicrm_points_sum hook

### ISSUE THREAD

**Issue by davidknoll** [futurefirst/uk.org.futurefirst.networks.civipoints#1]
There is a change in CRM_Utils_Hook::invoke from 4.4 to 4.5, from 5 to 6 parameters to be passed through to the hook function. This means when the custom hook invocation in CRM_Points_BAO_Points uses the 4.4 function signature, the hook suffix is passed where the 4.5/4.6 version of CRM_Utils_Hook expects the 6th parameter to the hook to be. This causes a whitescreen.

Need to check the Civi version in use and send the appropriate number of parameters?

**Comment by JohnFF** [comment]
I'd be tempted to try to default the parameter, or even use an enclosure
(PHP nameless function) if possible.

**Comment by davidknoll** [comment]
Fixed with e92ab4d, which checks the Civi version and calls CRM_Utils_Hook::invoke with the right number of parameters.
