### ISSUE TITLE
Filtering and display of points

### ISSUE THREAD

**Issue by davidknoll** [futurefirst/uk.org.futurefirst.networks.civipoints#3]
Add options to the points tab to select the point in time at which to show the points in effect, and to show all points even if not current.

**Comment by davidknoll** [comment]
Tackling this in branch 'filtering-display'. Will update the datatables in the points tabs using data from the AJAX API.

**Comment by JohnFF** [comment]
Hi Dave,

I'm really excited about this extension. I think tons of orgs will have use
cases for it.

When do you plan to merge CiviRules integration branch? To me that is a
very logical pairing.

John

**Comment by davidknoll** [comment]
Hi John,

There is a lot of reporting-related stuff to be done by Christmas, and
points is part of that. I don't know yet when it will be merged, there is
still more to be done and we may have to go live with a manual version to
get the reporting work over the line.

Thanks,
Dave

David Knoll

_Developer_

*Future First                        *

[image: NEW LOGO SMALL]

020 7239 8933 | www.futurefirst.org.uk | @futurefirstorg
http://twitter.com/futurefirstorg

Future First, 338 City Road, London, EC1V 2PY

Future First is the public name for Future First Alumni Limited, a
registered charity in England and Wales, charity number 1135638.

Standard disclaimer: this email and any attachments are confidential and
may also be privileged.  If you are not the addressee, do not disclose,
copy, circulate or in any other way use or rely on the information
contained in this email or any attachments.  If received in error, notify
the sender immediately and delete this email and any attachments from your
system.  Emails cannot be guaranteed to be secure or error free as the
message and any attachments could be intercepted, corrupted, lost, delayed,
incomplete or amended.  Future First does not accept legal responsibility
for the contents of this message or liability for damage caused by this
email or any attachments. Any views or opinions presented are only those of
the author and not those of Future First.

**Comment by davidknoll** [comment]
Completed with merge of https://github.com/futurefirst/uk.org.futurefirst.networks.civipoints/pull/11
