### ISSUE TITLE
If a contact has no points of one type, but has points of another type, no tabs show

### ISSUE THREAD

**Issue by davidknoll** [futurefirst/uk.org.futurefirst.networks.civipoints#8]
Suppose there are 3 types of points. A contact has never had any points of type 1 but has some of type 2 and some of type 3. None of the tabs show up.

If some points of type 1 are then granted to the contact, all the tabs show up.

**Comment by davidknoll** [comment]
The hook civipoints_civicrm_tabs is bombing out early. There is a return that should be a continue when checking whether a contact has had points of each type.

**Comment by JohnFF** [comment]
@davidknoll In my view - this is the wrong approach to showing the tab. I think that points should be connected to a type of contact (i.e. Student, School) and then display for contacts of that type regardless of if points have been added or not.

Just an opinion :)

**Comment by davidknoll** [comment]
I think we talked about that at the sprint, it's already a future enhancement: https://github.com/futurefirst/uk.org.futurefirst.networks.civipoints/issues/5

**Comment by JohnFF** [comment]
So it is - nice one!
